kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: pypicloud
    registry:
      from_secret: pypi_ecr_registry
    tags:
      - latest
      - ${DRONE_COMMIT}
